[package]
name = "ticktacktoe_ultimate"
version = "0.1.0"
authors = ["xarvic <xarvix@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.7.0"
itertools = "0.10.0"